# Generated by Django 3.2.3 on 2022-01-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211229_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Age',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='TeacherProfile/TeacherCV'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to='TeacherProfile/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question_one',
            field=models.BooleanField(default=False, verbose_name='Are you Deaf?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question_three',
            field=models.BooleanField(default=False, verbose_name='Do you have one from your family who are deaf?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question_two',
            field=models.BooleanField(default=False, verbose_name='Are you specialized in dealing with deaf people?'),
        ),
    ]
