# Generated by Django 3.2.8 on 2021-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211205_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='question_one',
            field=models.BooleanField(default=False, null=True, verbose_name='Are you Deaf?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_three',
            field=models.BooleanField(default=False, null=True, verbose_name='Do you have one from your family who are deaf?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_two',
            field=models.BooleanField(default=False, null=True, verbose_name='Are you specialized in dealing with deaf people?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
