# Generated by Django 3.2.3 on 2022-02-19 10:58

import Deaf_Website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220103_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to='TeacherProfile/', validators=[Deaf_Website.validators._ext_photo]),
        ),
    ]
