# Generated by Django 3.2.3 on 2021-12-06 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_accesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 18, 58, 26, 236098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
