# Generated by Django 3.2.3 on 2021-12-06 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211206_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 11, 51, 501680, tzinfo=utc)),
        ),
    ]
