# Generated by Django 3.2.3 on 2021-12-06 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accesstoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 23, 10, 53, 431755, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
