# Generated by Django 3.2.3 on 2021-12-07 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211207_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 0, 29, 11, 280408, tzinfo=utc)),
        ),
    ]
