# Generated by Django 3.2.3 on 2021-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_accesstoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
