# Generated by Django 3.2.3 on 2022-03-10 19:10

import Deaf_Website.models
import Deaf_Website.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('Words', 'photo'), validators=[Deaf_Website.validators._ext_photo])),
                ('video', models.FileField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('Words', 'video'), validators=[Deaf_Website.validators._ext_video])),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_agree_count', models.PositiveIntegerField(default=0)),
                ('user_disagree_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_agree', models.ManyToManyField(blank=True, related_name='user_agree', to=settings.AUTH_USER_MODEL)),
                ('user_disagree', models.ManyToManyField(blank=True, related_name='user_disagree', to=settings.AUTH_USER_MODEL)),
                ('word_attach', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Deaf_Website.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('WordUser', 'photo'), validators=[Deaf_Website.validators._ext_photo])),
                ('video', models.FileField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('WordUser', 'video'), validators=[Deaf_Website.validators._ext_video])),
                ('vote_teacher', models.BooleanField(null=True)),
                ('vote_percentage', models.CharField(blank=True, max_length=100)),
                ('teacher_approved', models.IntegerField(null=True)),
                ('teacher_denied', models.IntegerField(null=True)),
                ('teacher_num', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vote_approved', models.ManyToManyField(blank=True, related_name='vote_approved_relate', to=settings.AUTH_USER_MODEL)),
                ('vote_denied', models.ManyToManyField(blank=True, related_name='vote_denied_relate', to=settings.AUTH_USER_MODEL)),
                ('vote_nothing', models.ManyToManyField(blank=True, related_name='vote_nothing_relate', to=settings.AUTH_USER_MODEL)),
                ('word', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Deaf_Website.word')),
            ],
        ),
    ]
