# Generated by Django 3.2.3 on 2022-01-02 23:50

import Deaf_Website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=None, validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=None, validators=[Deaf_Website.validators._ext_video]),
        ),
    ]
