# Generated by Django 3.2.3 on 2021-11-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='slug',
            field=models.SlugField(default='teacher', unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='NegativeFeedBack',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='PositiveFeedBack',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='Deaf_Signs'),
        ),
    ]
