# Generated by Django 3.2.3 on 2022-02-09 08:52

import Deaf_Website.models
import Deaf_Website.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deaf_Website', '0002_auto_20220103_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='vote',
            field=models.ManyToManyField(related_name='user_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('Words', 'photo'), validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('Words', 'video'), validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('WordUser', 'photo'), validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Deaf_Website.models.UploadFiles('WordUser', 'video'), validators=[Deaf_Website.validators._ext_video]),
        ),
    ]
