# Generated by Django 3.2.3 on 2021-12-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0003_auto_20211204_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'verbose_name_plural': 'Uploaded Images'},
        ),
        migrations.AlterModelOptions(
            name='uploadedvideo',
            options={'verbose_name_plural': 'Uploaded Videos'},
        ),
        migrations.CreateModel(
            name='PendingUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Images/Deaf_Signs')),
                ('video', models.FileField(blank=True, upload_to='Videos/Deaf_Signs')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('PositiveFeedBack', models.IntegerField(default=0, null=True)),
                ('NegativeFeedBack', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Deaf_Website.category')),
            ],
            options={
                'verbose_name_plural': 'Pending Uploads',
            },
        ),
    ]
