# Generated by Django 3.2.3 on 2022-02-09 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deaf_Website', '0003_auto_20220209_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='user_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
