# Generated by Django 3.2.3 on 2021-12-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0003_auto_20211225_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
