# Generated by Django 3.2.3 on 2022-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0004_alter_worduser_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='vote_percentage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
