# Generated by Django 3.2.3 on 2021-12-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0004_auto_20211204_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguploads',
            name='Confrimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendinguploads',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Images/Deaf_Signs')),
                ('video', models.FileField(blank=True, upload_to='Videos/Deaf_Signs')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('PositiveFeedBack', models.IntegerField(default=0, null=True)),
                ('NegativeFeedBack', models.IntegerField(default=0, null=True)),
                ('addtoVideosClass', models.BooleanField(default=False)),
                ('addtoImagesClass', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Deaf_Website.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Deaf_Website.pendinguploads')),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
    ]
