# Generated by Django 3.2.3 on 2021-12-27 19:05

import Deaf_Website.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deaf_Website', '0004_alter_word_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_photo])),
                ('video', models.FileField(blank=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_video])),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
