# Generated by Django 3.2.3 on 2021-12-27 21:22

import Deaf_Website.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0005_auto_20211227_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worduser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='worduser',
            name='user',
        ),
        migrations.AddField(
            model_name='worduser',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Deaf_Website.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hesham', validators=[Deaf_Website.validators._ext_video]),
        ),
    ]
