# Generated by Django 3.2.3 on 2022-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0005_worduser_vote_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='vote_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
