# Generated by Django 3.2.3 on 2021-12-28 13:58

import Deaf_Website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0007_worduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='users/thumbnail'),
        ),
        migrations.AlterField(
            model_name='word',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/thumbnail', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='users/thumbnail', validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/thumbnail', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='users/thumbnail', validators=[Deaf_Website.validators._ext_video]),
        ),
    ]
