# Generated by Django 3.2.3 on 2021-12-29 02:29

import Deaf_Website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0008_auto_20211228_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fuck', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='word',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='fuck'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='fuck', validators=[Deaf_Website.validators._ext_video]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fuck', validators=[Deaf_Website.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='fuck', validators=[Deaf_Website.validators._ext_video]),
        ),
    ]
