# Generated by Django 3.2.3 on 2022-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0016_alter_worduser_vote_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='teacher_approved',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='worduser',
            name='teacher_num',
            field=models.PositiveIntegerField(default=2, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='vote_teacher',
            field=models.BooleanField(choices=[(None, 'لم يتم الإختيار'), (True, 'نعم'), (False, 'لا')], default=None, null=True),
        ),
    ]
