# Generated by Django 3.2.3 on 2022-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0017_auto_20220211_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='teacher_approved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='teacher_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
