# Generated by Django 3.2.3 on 2022-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0019_auto_20220211_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='teacher_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
