# Generated by Django 3.2.3 on 2022-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0021_alter_worduser_teacher_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='teacher_approved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='teacher_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
