# Generated by Django 3.2.3 on 2022-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0022_auto_20220211_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='teacher_approved',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='teacher_num',
            field=models.IntegerField(null=True),
        ),
    ]
