# Generated by Django 3.2.3 on 2022-02-17 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deaf_Website', '0024_auto_20220215_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='vote_nothing',
            field=models.ManyToManyField(blank=True, related_name='vote_nothing_relate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='vote_approved',
            field=models.ManyToManyField(blank=True, related_name='vote_approved_relate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='vote_denied',
            field=models.ManyToManyField(blank=True, related_name='vote_denied_relate', to=settings.AUTH_USER_MODEL),
        ),
    ]
