# Generated by Django 3.2.3 on 2022-02-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0025_auto_20220217_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduser',
            name='vote_teacher',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_link', to='Deaf_Website.word'),
        ),
    ]
