# Generated by Django 3.2.3 on 2022-02-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0026_auto_20220218_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_attach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Deaf_Website.word'),
        ),
        migrations.AlterField(
            model_name='worduser',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Deaf_Website.word'),
        ),
    ]
