# Generated by Django 3.2.3 on 2022-02-25 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deaf_Website', '0027_auto_20220218_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_agree',
            field=models.ManyToManyField(blank=True, related_name='user_agree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='user_disagree',
            field=models.ManyToManyField(blank=True, related_name='user_disagree', to=settings.AUTH_USER_MODEL),
        ),
    ]
