# Generated by Django 3.2.3 on 2022-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deaf_Website', '0028_auto_20220225_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_agree_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='user_disagree_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
